name: sanity-check

on:
  push:
    branches:
      - "main"
      
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: build
    runs-on: self-hosted
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3 \
            python3-pip \
            nasm \
            iasl \
            uuid-dev \
            libglib2.0-dev \
            libpixman-1-dev \
            libgtk-3-dev \
            ninja-build \
            flex \
            bison

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: true 

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Apply Patches
        run: ./scripts/apply_patches.sh

      - name: Build All
        run: ./scripts/build_all.sh